# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@babel/helper-validator-identifier-7.16.7" = {
      name = "_at_babel_slash_helper-validator-identifier";
      packageName = "@babel/helper-validator-identifier";
      version = "7.16.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-validator-identifier/-/helper-validator-identifier-7.16.7.tgz";
        sha512 = "hsEnFemeiW4D08A5gUAZxLBTXpZ39P+a+DGDsHw1yxqyQ/jzFEnxf5uTEGp+3bzAbNOxU1paTgYS4ECU/IgfDw==";
      };
    };
    "@babel/highlight-7.17.9" = {
      name = "_at_babel_slash_highlight";
      packageName = "@babel/highlight";
      version = "7.17.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/highlight/-/highlight-7.17.9.tgz";
        sha512 = "J9PfEKCbFIv2X5bjTMiZu6Vf341N05QIY+d6FvVKynkG1S7G0j3I0QoRtWIrXhZ+/Nlb5Q0MzqL7TokEJ5BNHg==";
      };
    };
    "@littlethings/log-1.4.0" = {
      name = "_at_littlethings_slash_log";
      packageName = "@littlethings/log";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@littlethings/log/-/log-1.4.0.tgz";
        sha512 = "KuGDAaKCi18wT1PESoBMon3nJlnnVREBqLrTxdWbAKb/IXVAbGyB3Ie3Tg9e69xab43SWtn+f2XgBCsE5MbCoA==";
      };
    };
    "@littlethings/log-3.0.1" = {
      name = "_at_littlethings_slash_log";
      packageName = "@littlethings/log";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@littlethings/log/-/log-3.0.1.tgz";
        sha512 = "koxoqRVFdyiL7ccRBTaSiOsejd5eQUUySJ7gbOWazpHj0GWuS/bAS98c7z3H7P2ozFnV/nTyGRPF6DQv28ArqQ==";
      };
    };
    "@littlethings/test-1.2.1" = {
      name = "_at_littlethings_slash_test";
      packageName = "@littlethings/test";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@littlethings/test/-/test-1.2.1.tgz";
        sha512 = "GVVmZB+Z4mlG79sq+gCq8xu/zl6AE4nNfuQRfeki0NLTCKi/eW67PN5e5vxJKbEKK4Mh4KvMh2EUSekkf10PeA==";
      };
    };
    "@starters/core-1.8.0" = {
      name = "_at_starters_slash_core";
      packageName = "@starters/core";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@starters/core/-/core-1.8.0.tgz";
        sha512 = "BV6vriLt3GomQVIBb3TYMNNEJX+VaYhHw4CJe5BU07en2ikbNO9SWqB1LSxJ5IAWoNvuu7uhtM4jEGpZQ+7Btw==";
      };
    };
    "@types/node-10.17.60" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "10.17.60";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-10.17.60.tgz";
        sha512 = "F0KIgDJfy2nA3zMLmWGKxcH2ZVEtCZXHHdOQs2gSaQ27+lNeEfGxzkIw90aXswATX7AZ33tahPbzy6KAfUreVw==";
      };
    };
    "abort-controller-3.0.0" = {
      name = "abort-controller";
      packageName = "abort-controller";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/abort-controller/-/abort-controller-3.0.0.tgz";
        sha512 = "h8lQ8tacZYnR3vNQTgibj+tODHI5/+l06Au2Pcriv/Gmet0eaj4TwWH41sO9wnHDiQsEj19q0drzdWdeAHtweg==";
      };
    };
    "ansi-colors-4.1.1" = {
      name = "ansi-colors";
      packageName = "ansi-colors";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-colors/-/ansi-colors-4.1.1.tgz";
        sha512 = "JoX0apGbHaUJBNl6yF+p6JAFYZ666/hhCGKN5t9QFjbJQKUU/g8MNbFDbvfrgKXvI1QpZplPOnwIo99lX/AAmA==";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "arg-4.1.3" = {
      name = "arg";
      packageName = "arg";
      version = "4.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/arg/-/arg-4.1.3.tgz";
        sha512 = "58S9QDqG0Xx27YwPSt9fJxivjYl432YCwfDMfZ+71RAqUrZef7LrKQZ3LHLOwCS4FLNBplP533Zx895SeOCHvA==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "camel-case-4.1.2" = {
      name = "camel-case";
      packageName = "camel-case";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/camel-case/-/camel-case-4.1.2.tgz";
        sha512 = "gxGWBrTT1JuMx6R+o5PTXMmUnhnVzLQ9SNutD4YqKtI6ap897t3tKECYla6gCWEkplXnlNybEkZg9GEGxKFCgw==";
      };
    };
    "capital-case-1.0.4" = {
      name = "capital-case";
      packageName = "capital-case";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/capital-case/-/capital-case-1.0.4.tgz";
        sha512 = "ds37W8CytHgwnhGGTi88pcPyR15qoNkOpYwmMMfnWqqWgESapLqvDx6huFjQ5vqWSn2Z06173XNA7LtMOeUh1A==";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "chalk-4.1.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-4.1.2.tgz";
        sha512 = "oKnbhFyRIXpUuez8iBMmyEa4nbj4IOQyuhc/wy9kY7/WVPcwIO9VA668Pu8RkO7+0G76SLROeyw9CpQ061i4mA==";
      };
    };
    "change-case-4.1.2" = {
      name = "change-case";
      packageName = "change-case";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/change-case/-/change-case-4.1.2.tgz";
        sha512 = "bSxY2ws9OtviILG1EiY5K7NNxkqg/JnRnFxLtKQ96JaviiIxi7djMrSd0ECT9AC+lttClmYwKw53BWpOMblo7A==";
      };
    };
    "clef-parse-0.1.2" = {
      name = "clef-parse";
      packageName = "clef-parse";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/clef-parse/-/clef-parse-0.1.2.tgz";
        sha512 = "rHmFEdkVk78nuoUavExHOpjohRalKP/JKriSZbRPYRiaxGM8eD/LI1UFFqxE4MH9XFCc5cKqFERSPy4jQu01fA==";
      };
    };
    "clefairy-0.2.1" = {
      name = "clefairy";
      packageName = "clefairy";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/clefairy/-/clefairy-0.2.1.tgz";
        sha512 = "DxCrzJhy3Io9vmpTRymt4AFjwx2fDnzetcLzOk0NyKU3buIX/i1FCo9/AQKN9hPPm3QgrLFc+UaokhxBL80Zbw==";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "commander-2.20.3" = {
      name = "commander";
      packageName = "commander";
      version = "2.20.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.20.3.tgz";
        sha512 = "GpVkmM8vF2vQUkj2LvZmD35JxeJOLCwJ9cUkugyk2nuhbv3+mJvpLYYt+0+USMxE+oj+ey/lJEnhZw75x/OMcQ==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "constant-case-3.0.4" = {
      name = "constant-case";
      packageName = "constant-case";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/constant-case/-/constant-case-3.0.4.tgz";
        sha512 = "I2hSBi7Vvs7BEuJDr5dDHfzb/Ruj3FyvFyh7KLilAjNQw3Be+xgqUBA2W6scVEcL0hL1dwPRtIqEPVUCKkSsyQ==";
      };
    };
    "copy-dir-1.3.0" = {
      name = "copy-dir";
      packageName = "copy-dir";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/copy-dir/-/copy-dir-1.3.0.tgz";
        sha512 = "Q4+qBFnN4bwGwvtXXzbp4P/4iNk0MaiGAzvQ8OiMtlLjkIKjmNN689uVzShSM0908q7GoFHXIPx4zi75ocoaHw==";
      };
    };
    "dot-case-3.0.4" = {
      name = "dot-case";
      packageName = "dot-case";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/dot-case/-/dot-case-3.0.4.tgz";
        sha512 = "Kv5nKlh6yRrdrGvxeJ2e5y2eRUpkUosIW4A2AS38zwSz27zu7ufDwQPi5Jhs3XAlGNetl3bmnGhQsMtkKJnj3w==";
      };
    };
    "ejs-2.7.4" = {
      name = "ejs";
      packageName = "ejs";
      version = "2.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/ejs/-/ejs-2.7.4.tgz";
        sha512 = "7vmuyh5+kuUyJKePhQfRQBhXV5Ce+RnaeeQArKu1EAMpL3WbgMt5WG6uQZpEVvYSSsxMXRKOewtDk9RaTKXRlA==";
      };
    };
    "enquirer-2.3.6" = {
      name = "enquirer";
      packageName = "enquirer";
      version = "2.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/enquirer/-/enquirer-2.3.6.tgz";
        sha512 = "yjNnPr315/FjS4zIsUxYguYUPP2e1NK4d7E7ZOLiyYCcbFBiTMyID+2wvm2w6+pZ/odMA7cRkjhsPbltwBOrLg==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "event-target-shim-5.0.1" = {
      name = "event-target-shim";
      packageName = "event-target-shim";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/event-target-shim/-/event-target-shim-5.0.1.tgz";
        sha512 = "i/2XbnSz/uxRCU6+NdVJgKWDTM427+MqYbkQzD321DuCQJUqOuJKIA0IM2+W2xtYHdKOmZ4dR6fExsd4SXL+WQ==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "giturl-1.0.1" = {
      name = "giturl";
      packageName = "giturl";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/giturl/-/giturl-1.0.1.tgz";
        sha512 = "wQourBdI13n8tbjcZTDl6k+ZrCRMU6p9vfp9jknZq+zfWc8xXNztpZFM4XkPHVzHcMSUZxEMYYKZjIGkPlei6Q==";
      };
    };
    "glob-7.2.0" = {
      name = "glob";
      packageName = "glob";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.2.0.tgz";
        sha512 = "lmLf6gtyrPq8tTjSmrO94wBeQbFR3HbLHbuyD69wuyQkImp2hWqMGB47OX65FBkPffO641IP9jWa1z4ivqG26Q==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha1 = "b5d454dc2199ae225699f3467e5a07f3b955bafd";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "header-case-2.0.4" = {
      name = "header-case";
      packageName = "header-case";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/header-case/-/header-case-2.0.4.tgz";
        sha512 = "H/vuk5TEEVZwrR0lp2zed9OCo1uAILMlx0JEMgC26rzyJJ3N1v6XkwHHXJQdR2doSjcGPM6OKPYoJgf0plJ11Q==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "interpret-1.4.0" = {
      name = "interpret";
      packageName = "interpret";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/interpret/-/interpret-1.4.0.tgz";
        sha512 = "agE4QfB2Lkp9uICn7BAqoscw4SZP9kTE2hxiFI3jBPmXJfdqiahTbUuKGsMoN2GtqL9AxhYioAcVvgsb1HvRbA==";
      };
    };
    "is-core-module-2.9.0" = {
      name = "is-core-module";
      packageName = "is-core-module";
      version = "2.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-core-module/-/is-core-module-2.9.0.tgz";
        sha512 = "+5FPy5PnwmO3lvfMb0AsoPaBG+5KHUI0wYFXOtYPnVVVspTFUuMZNfNaNVRt3FZadstu2c8x23vykRW/NBoU6A==";
      };
    };
    "is-url-1.2.4" = {
      name = "is-url";
      packageName = "is-url";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-url/-/is-url-1.2.4.tgz";
        sha512 = "ITvGim8FhRiYe4IQ5uHSkj7pVaPDrCTkNd3yq3cV7iZAcJdHTUMPMEHcqSOy9xZ9qFenQCvi+2wjH9a1nXqHww==";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha1 = "e8fbf374dc556ff8947a10dcb0572d633f2cfa10";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "json5-2.2.1" = {
      name = "json5";
      packageName = "json5";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-2.2.1.tgz";
        sha512 = "1hqLFMSrGHRHxav9q9gNjJ5EXznIxGVO09xQRrwplcS8qs28pZ8s8hupZAmqDwZUmVZ2Qb2jnyPOWcDH8m8dlA==";
      };
    };
    "kleur-4.1.4" = {
      name = "kleur";
      packageName = "kleur";
      version = "4.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/kleur/-/kleur-4.1.4.tgz";
        sha512 = "8QADVssbrFjivHWQU7KkMgptGTl6WAcSdlbBPY4uNF+mWr6DGcKrvY2w4FQJoXch7+fKMjj0dRrL75vk3k23OA==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "lower-case-2.0.2" = {
      name = "lower-case";
      packageName = "lower-case";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lower-case/-/lower-case-2.0.2.tgz";
        sha512 = "7fm3l3NAF9WfN6W3JOmf5drwpVqX78JtoGJ3A6W0a6ZnldM41w2fV5D490psKFTpMds8TJse/eHLFFsNHHjHgg==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "make-module-env-1.0.1" = {
      name = "make-module-env";
      packageName = "make-module-env";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/make-module-env/-/make-module-env-1.0.1.tgz";
        sha512 = "EPNN4mZs1qyWsr7KgKoKBSg+CVpt0yhyFJfIcUTTH9i4PDOVGI/7+ohySaz1Ak6XemVqjy6b3EUNARQyLhRnuw==";
      };
    };
    "minimatch-3.1.2" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.1.2.tgz";
        sha512 = "J7p63hRiAjw1NDEww1W7i37+ByIrOWO5XQQAzZ3VOcL0PNybwpfmV/N05zFAzwQ9USyEcX6t3UO+K5aqBQOIHw==";
      };
    };
    "mkdirp-1.0.4" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-1.0.4.tgz";
        sha512 = "vVqVZQyf3WLx2Shd0qJ9xuvqgAyKPLAiqITEtqW0oIUjzo3PePDd6fW9iFz30ef7Ysp/oiWqbhszeGWW2T6Gzw==";
      };
    };
    "no-case-3.0.4" = {
      name = "no-case";
      packageName = "no-case";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/no-case/-/no-case-3.0.4.tgz";
        sha512 = "fgAN3jGAh+RoxUGZHTSOLJIqUc2wmoBwGR4tbpNAKmmovFoWq0OdRkb0VkldReO2a2iBT/OEulG9XSUc10r3zg==";
      };
    };
    "npm-path-2.0.4" = {
      name = "npm-path";
      packageName = "npm-path";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-path/-/npm-path-2.0.4.tgz";
        sha512 = "IFsj0R9C7ZdR5cP+ET342q77uSRdtWOlWpih5eC+lu29tIDbNEgDbzgVJ5UFvYHWhxDZ5TFkJafFioO0pPQjCw==";
      };
    };
    "npm-which-3.0.1" = {
      name = "npm-which";
      packageName = "npm-which";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-which/-/npm-which-3.0.1.tgz";
        sha1 = "9225f26ec3a285c209cae67c3b11a6b4ab7140aa";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "param-case-3.0.4" = {
      name = "param-case";
      packageName = "param-case";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/param-case/-/param-case-3.0.4.tgz";
        sha512 = "RXlj7zCYokReqWpOPH9oYivUzLYZ5vAPIfEmCTNViosC78F8F0H9y7T7gG2M39ymgutxF5gcFEsyZQSph9Bp3A==";
      };
    };
    "pascal-case-3.1.2" = {
      name = "pascal-case";
      packageName = "pascal-case";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pascal-case/-/pascal-case-3.1.2.tgz";
        sha512 = "uWlGT3YSnK9x3BQJaOdcZwrnV6hPpd8jFH1/ucpiLRPh/2zCVJKS19E4GvYHvaCcACn3foXZ0cLB9Wrx1KGe5g==";
      };
    };
    "path-case-3.0.4" = {
      name = "path-case";
      packageName = "path-case";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-case/-/path-case-3.0.4.tgz";
        sha512 = "qO4qCFjXqVTrcbPt/hQfhTQ+VhFsqNKOPtytgNKkKxSoEp3XPUQ8ObFuePylOIok5gjn69ry8XiULxCwot3Wfg==";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "path-parse-1.0.7" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.7.tgz";
        sha512 = "LDJzPVEEEPR+y48z93A0Ed0yXb8pAByGWo/k5YYdYgpY2/2EsOsksJrq7lOHxryrVOn1ejG6oAp8ahvOIQD8sw==";
      };
    };
    "pretty-print-error-1.1.1" = {
      name = "pretty-print-error";
      packageName = "pretty-print-error";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pretty-print-error/-/pretty-print-error-1.1.1.tgz";
        sha512 = "xl5LI8vnfNExJzIpCeyoTVGHsKCyX5GSrK8IPoy6FJZQotqveE41guzwwPTEAWLJAcuq1s5xz4EbGQvM/KGwjw==";
      };
    };
    "rechoir-0.6.2" = {
      name = "rechoir";
      packageName = "rechoir";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rechoir/-/rechoir-0.6.2.tgz";
        sha1 = "85204b54dba82d5742e28c96756ef43af50e3384";
      };
    };
    "render-in-place-1.0.2" = {
      name = "render-in-place";
      packageName = "render-in-place";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/render-in-place/-/render-in-place-1.0.2.tgz";
        sha512 = "TS8Cfud/L1Td2ksEgQAIcRXgzyCb7cD4U1cb1kPQDelECPGrfjqp5IaN/R+WdCVJ9XxKEv95PWW6r9Uak+iR9g==";
      };
    };
    "resolve-1.22.0" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.22.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.22.0.tgz";
        sha512 = "Hhtrw0nLeSrFQ7phPp4OOcVjLPIeMnRlr5mcnVuMe7M/7eBn98A3hmFRLoFo3DLZkivSYwhRUJTyPyWAk56WLw==";
      };
    };
    "rimraf-3.0.2" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-3.0.2.tgz";
        sha512 = "JZkJMZkAGFFPP2YqXZXPbMlMBgsxzE8ILs4lMIX/2o0L9UBw9O/Y3o6wFw/i9YLapcUJWwqbi3kdxIPdC62TIA==";
      };
    };
    "semver-7.3.7" = {
      name = "semver";
      packageName = "semver";
      version = "7.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.3.7.tgz";
        sha512 = "QlYTucUYOews+WeEujDoEGziz4K6c47V/Bd+LjSSYcA94p+DmINdf7ncaUinThfvZyu13lN9OY1XDxt8C0Tw0g==";
      };
    };
    "sentence-case-3.0.4" = {
      name = "sentence-case";
      packageName = "sentence-case";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/sentence-case/-/sentence-case-3.0.4.tgz";
        sha512 = "8LS0JInaQMCRoQ7YUytAo/xUu5W2XnQxV2HI/6uM6U7CITS1RqPElr30V6uIqyMKM9lJGRVFy5/4CuzcixNYSg==";
      };
    };
    "shelljs-0.8.5" = {
      name = "shelljs";
      packageName = "shelljs";
      version = "0.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/shelljs/-/shelljs-0.8.5.tgz";
        sha512 = "TiwcRcrkhHvbrZbnRcFYMLl30Dfov3HKqzp5tO5b4pt6G/SezKcYhmDg15zXVBswHmctSAQKznqNW2LO5tTDow==";
      };
    };
    "snake-case-3.0.4" = {
      name = "snake-case";
      packageName = "snake-case";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/snake-case/-/snake-case-3.0.4.tgz";
        sha512 = "LAOh4z89bGQvl9pFfNF8V146i7o7/CqFPbqzYgP+yYzDIDeS9HaNFtXABamRW+AQzEVODcvE79ljJ+8a9YSdMg==";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "supports-color-7.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz";
        sha512 = "qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
      };
    };
    "supports-preserve-symlinks-flag-1.0.0" = {
      name = "supports-preserve-symlinks-flag";
      packageName = "supports-preserve-symlinks-flag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-preserve-symlinks-flag/-/supports-preserve-symlinks-flag-1.0.0.tgz";
        sha512 = "ot0WnXS9fgdkgIcePe6RHNk1WA8+muPa6cSjeR3V8K27q9BB1rTE3R1p7Hv0z1ZyAc8s6Vvv8DIyWf681MAt0w==";
      };
    };
    "tslib-2.3.1" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.3.1.tgz";
        sha512 = "77EbyPPpMz+FRFRuAFlWMtmgUWGe9UOG2Z25NqCwiIjRhOf5iKGuzSe5P2w1laq+FkRy4p+PCuVkJSGkzTEKVw==";
      };
    };
    "upper-case-2.0.2" = {
      name = "upper-case";
      packageName = "upper-case";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/upper-case/-/upper-case-2.0.2.tgz";
        sha512 = "KgdgDGJt2TpuwBUIjgG6lzw2GWFRCW9Qkfkiv0DxqHHLYJHmtmdUIKcZd8rHgFSjopVTlw6ggzCm1b8MFQwikg==";
      };
    };
    "upper-case-first-2.0.2" = {
      name = "upper-case-first";
      packageName = "upper-case-first";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/upper-case-first/-/upper-case-first-2.0.2.tgz";
        sha512 = "514ppYHBaKwfJRK/pNC6c/OxfGa0obSnAl106u97Ed0I625Nin96KAjttZF6ZL3e1XLtphxnqrOi9iWgm+u+bg==";
      };
    };
    "which-1.3.1" = {
      name = "which";
      packageName = "which";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.3.1.tgz";
        sha512 = "HxJdYWq1MTIQbJ3nw0cqssHoTNU267KlrDuGZ1WYlxDStUtKUhOaJmh112/TZmHxxUfuJqPXSOm7tDyas0OSIQ==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
  };
in
{
  "@jakehamilton/titan-5.11.1" = nodeEnv.buildNodePackage {
    name = "_at_jakehamilton_slash_titan";
    packageName = "@jakehamilton/titan";
    version = "5.11.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/@jakehamilton/titan/-/titan-5.11.1.tgz";
      sha512 = "sTrCJod1HJJevZvwJqWZIcb+ZqQbpDCC0LGobUMj+ohQPpFHnvja42v7YvWTB8DiaGOOy5JSF2ybUTFgXKjx0A==";
    };
    dependencies = [
      sources."@littlethings/log-3.0.1"
      (sources."@littlethings/test-1.2.1" // {
        dependencies = [
          sources."@littlethings/log-1.4.0"
        ];
      })
      (sources."@starters/core-1.8.0" // {
        dependencies = [
          sources."kleur-4.1.4"
        ];
      })
      sources."@types/node-10.17.60"
      sources."abort-controller-3.0.0"
      sources."ansi-colors-4.1.1"
      sources."ansi-styles-4.3.0"
      sources."arg-4.1.3"
      sources."balanced-match-1.0.2"
      sources."brace-expansion-1.1.11"
      sources."chalk-4.1.2"
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."commander-2.20.3"
      sources."concat-map-0.0.1"
      sources."copy-dir-1.3.0"
      sources."ejs-2.7.4"
      sources."enquirer-2.3.6"
      sources."event-target-shim-5.0.1"
      sources."fs.realpath-1.0.0"
      sources."giturl-1.0.1"
      sources."glob-7.2.0"
      sources."has-flag-4.0.0"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."is-url-1.2.4"
      sources."isexe-2.0.0"
      sources."kleur-4.1.4"
      sources."lru-cache-6.0.0"
      sources."minimatch-3.1.2"
      sources."mkdirp-1.0.4"
      sources."npm-path-2.0.4"
      sources."npm-which-3.0.1"
      sources."once-1.4.0"
      sources."path-is-absolute-1.0.1"
      sources."render-in-place-1.0.2"
      sources."rimraf-3.0.2"
      sources."semver-7.3.7"
      sources."supports-color-7.2.0"
      sources."which-1.3.1"
      sources."wrappy-1.0.2"
      sources."yallist-4.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A little tool for big (monorepo) projects.";
      homepage = "https://github.com/jakehamilton/packages";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@suchipi/at-js-0.4.0" = nodeEnv.buildNodePackage {
    name = "_at_suchipi_slash_at-js";
    packageName = "@suchipi/at-js";
    version = "0.4.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@suchipi/at-js/-/at-js-0.4.0.tgz";
      sha512 = "CxaQaLKyH+UznHzoubI60j45x+ms7eZ8joAZ7Bnp5fhSJc5XPsS+Xc5fGaf5Y2TNyJREriDW/nIjG37S0qvt3w==";
    };
    dependencies = [
      sources."@babel/helper-validator-identifier-7.16.7"
      sources."@babel/highlight-7.17.9"
      sources."ansi-styles-3.2.1"
      sources."balanced-match-1.0.2"
      sources."brace-expansion-1.1.11"
      sources."camel-case-4.1.2"
      sources."capital-case-1.0.4"
      sources."chalk-2.4.2"
      sources."change-case-4.1.2"
      sources."clef-parse-0.1.2"
      sources."clefairy-0.2.1"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."concat-map-0.0.1"
      sources."constant-case-3.0.4"
      sources."dot-case-3.0.4"
      sources."escape-string-regexp-1.0.5"
      sources."fs.realpath-1.0.0"
      sources."function-bind-1.1.1"
      sources."glob-7.2.0"
      sources."has-1.0.3"
      sources."has-flag-3.0.0"
      sources."header-case-2.0.4"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."interpret-1.4.0"
      sources."is-core-module-2.9.0"
      sources."js-tokens-4.0.0"
      sources."json5-2.2.1"
      sources."kleur-4.1.4"
      sources."lodash-4.17.21"
      sources."lower-case-2.0.2"
      sources."make-module-env-1.0.1"
      sources."minimatch-3.1.2"
      sources."no-case-3.0.4"
      sources."once-1.4.0"
      sources."param-case-3.0.4"
      sources."pascal-case-3.1.2"
      sources."path-case-3.0.4"
      sources."path-is-absolute-1.0.1"
      sources."path-parse-1.0.7"
      sources."pretty-print-error-1.1.1"
      sources."rechoir-0.6.2"
      sources."resolve-1.22.0"
      sources."sentence-case-3.0.4"
      sources."shelljs-0.8.5"
      sources."snake-case-3.0.4"
      sources."supports-color-5.5.0"
      sources."supports-preserve-symlinks-flag-1.0.0"
      sources."tslib-2.3.1"
      sources."upper-case-2.0.2"
      sources."upper-case-first-2.0.2"
      sources."wrappy-1.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "unix stdin-pipe-based tools for transforming data with JavaScript";
      homepage = "https://github.com/suchipi/at-js#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
