# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@babel/helper-validator-identifier-7.19.1" = {
      name = "_at_babel_slash_helper-validator-identifier";
      packageName = "@babel/helper-validator-identifier";
      version = "7.19.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-validator-identifier/-/helper-validator-identifier-7.19.1.tgz";
        sha512 = "awrNfaMtnHUr653GgGEs++LlAvW6w+DcPrOliSMXWCKo597CwL5Acf/wWdNkf/tfEQE3mjkeD1YOVZOUV/od1w==";
      };
    };
    "@babel/highlight-7.18.6" = {
      name = "_at_babel_slash_highlight";
      packageName = "@babel/highlight";
      version = "7.18.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/highlight/-/highlight-7.18.6.tgz";
        sha512 = "u7stbOuYjaPezCuLj29hNW1v64M2Md2qupEKP1fHc7WdOA3DgLh37suiSrZYY7haUB7iBeQZ9P1uiRF359do3g==";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "camel-case-4.1.2" = {
      name = "camel-case";
      packageName = "camel-case";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/camel-case/-/camel-case-4.1.2.tgz";
        sha512 = "gxGWBrTT1JuMx6R+o5PTXMmUnhnVzLQ9SNutD4YqKtI6ap897t3tKECYla6gCWEkplXnlNybEkZg9GEGxKFCgw==";
      };
    };
    "capital-case-1.0.4" = {
      name = "capital-case";
      packageName = "capital-case";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/capital-case/-/capital-case-1.0.4.tgz";
        sha512 = "ds37W8CytHgwnhGGTi88pcPyR15qoNkOpYwmMMfnWqqWgESapLqvDx6huFjQ5vqWSn2Z06173XNA7LtMOeUh1A==";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "change-case-4.1.2" = {
      name = "change-case";
      packageName = "change-case";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/change-case/-/change-case-4.1.2.tgz";
        sha512 = "bSxY2ws9OtviILG1EiY5K7NNxkqg/JnRnFxLtKQ96JaviiIxi7djMrSd0ECT9AC+lttClmYwKw53BWpOMblo7A==";
      };
    };
    "clef-parse-0.1.2" = {
      name = "clef-parse";
      packageName = "clef-parse";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/clef-parse/-/clef-parse-0.1.2.tgz";
        sha512 = "rHmFEdkVk78nuoUavExHOpjohRalKP/JKriSZbRPYRiaxGM8eD/LI1UFFqxE4MH9XFCc5cKqFERSPy4jQu01fA==";
      };
    };
    "clefairy-0.2.1" = {
      name = "clefairy";
      packageName = "clefairy";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/clefairy/-/clefairy-0.2.1.tgz";
        sha512 = "DxCrzJhy3Io9vmpTRymt4AFjwx2fDnzetcLzOk0NyKU3buIX/i1FCo9/AQKN9hPPm3QgrLFc+UaokhxBL80Zbw==";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha512 = "72fSenhMw2HZMTVHeCA9KCmpEIbzWiQsjN+BHcBbS9vr1mtt+vJjPdksIBNUmKAW8TFUDPJK5SUU3QhE9NEXDw==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha512 = "/Srv4dswyQNBfohGpz9o6Yb3Gz3SrUDqBH5rTuhGR7ahtlbYKnVxw2bCFMRljaA7EXHaXZ8wsHdodFvbkhKmqg==";
      };
    };
    "constant-case-3.0.4" = {
      name = "constant-case";
      packageName = "constant-case";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/constant-case/-/constant-case-3.0.4.tgz";
        sha512 = "I2hSBi7Vvs7BEuJDr5dDHfzb/Ruj3FyvFyh7KLilAjNQw3Be+xgqUBA2W6scVEcL0hL1dwPRtIqEPVUCKkSsyQ==";
      };
    };
    "dot-case-3.0.4" = {
      name = "dot-case";
      packageName = "dot-case";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/dot-case/-/dot-case-3.0.4.tgz";
        sha512 = "Kv5nKlh6yRrdrGvxeJ2e5y2eRUpkUosIW4A2AS38zwSz27zu7ufDwQPi5Jhs3XAlGNetl3bmnGhQsMtkKJnj3w==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha512 = "vbRorB5FUQWvla16U8R/qgaFIya2qGzwDrNmCZuYKrbdSUMG6I1ZCGQRefkRVhuOkIGVne7BQ35DSfo1qvJqFg==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha512 = "OO0pH2lK6a0hZnAdau5ItzHPI6pUlvI7jMVnxUQRtw4owF2wk8lOSabtGDCTP4Ggrg2MbGnWO9X8K1t4+fGMDw==";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "glob-7.2.3" = {
      name = "glob";
      packageName = "glob";
      version = "7.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.2.3.tgz";
        sha512 = "nFR0zLpU2YCaRxwoCJvL6UvCH2JFyFVIvwTLsIf21AuHlMskA1hhTdk+LlYJtOlYt9v6dvszD2BGRqBL+iQK9Q==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha512 = "sKJf1+ceQBr4SMkvQnBDNDtf4TXpVhVGateu0t918bl30FnbE2m4vNLX+VWe/dpjlb+HugGYzW7uQXH98HPEYw==";
      };
    };
    "header-case-2.0.4" = {
      name = "header-case";
      packageName = "header-case";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/header-case/-/header-case-2.0.4.tgz";
        sha512 = "H/vuk5TEEVZwrR0lp2zed9OCo1uAILMlx0JEMgC26rzyJJ3N1v6XkwHHXJQdR2doSjcGPM6OKPYoJgf0plJ11Q==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha512 = "k92I/b08q4wvFscXCLvqfsHCrjrF7yiXsQuIVvVE7N82W3+aqpzuUdBbfhWcy/FZR3/4IgflMgKLOsvPDrGCJA==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "interpret-1.4.0" = {
      name = "interpret";
      packageName = "interpret";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/interpret/-/interpret-1.4.0.tgz";
        sha512 = "agE4QfB2Lkp9uICn7BAqoscw4SZP9kTE2hxiFI3jBPmXJfdqiahTbUuKGsMoN2GtqL9AxhYioAcVvgsb1HvRbA==";
      };
    };
    "is-core-module-2.11.0" = {
      name = "is-core-module";
      packageName = "is-core-module";
      version = "2.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-core-module/-/is-core-module-2.11.0.tgz";
        sha512 = "RRjxlvLDkD1YJwDbroBHMb+cukurkDWNyHx7D3oNB5x9rb5ogcksMC5wHCadcXoo67gVr/+3GFySh3134zi6rw==";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "json5-2.2.1" = {
      name = "json5";
      packageName = "json5";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-2.2.1.tgz";
        sha512 = "1hqLFMSrGHRHxav9q9gNjJ5EXznIxGVO09xQRrwplcS8qs28pZ8s8hupZAmqDwZUmVZ2Qb2jnyPOWcDH8m8dlA==";
      };
    };
    "kleur-4.1.5" = {
      name = "kleur";
      packageName = "kleur";
      version = "4.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/kleur/-/kleur-4.1.5.tgz";
        sha512 = "o+NO+8WrRiQEE4/7nwRJhN1HWpVmJm511pBHUxPLtp0BUISzlBplORYSmTclCnJvQq2tKu/sgl3xVpkc7ZWuQQ==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "lower-case-2.0.2" = {
      name = "lower-case";
      packageName = "lower-case";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lower-case/-/lower-case-2.0.2.tgz";
        sha512 = "7fm3l3NAF9WfN6W3JOmf5drwpVqX78JtoGJ3A6W0a6ZnldM41w2fV5D490psKFTpMds8TJse/eHLFFsNHHjHgg==";
      };
    };
    "make-module-env-1.0.1" = {
      name = "make-module-env";
      packageName = "make-module-env";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/make-module-env/-/make-module-env-1.0.1.tgz";
        sha512 = "EPNN4mZs1qyWsr7KgKoKBSg+CVpt0yhyFJfIcUTTH9i4PDOVGI/7+ohySaz1Ak6XemVqjy6b3EUNARQyLhRnuw==";
      };
    };
    "minimatch-3.1.2" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.1.2.tgz";
        sha512 = "J7p63hRiAjw1NDEww1W7i37+ByIrOWO5XQQAzZ3VOcL0PNybwpfmV/N05zFAzwQ9USyEcX6t3UO+K5aqBQOIHw==";
      };
    };
    "no-case-3.0.4" = {
      name = "no-case";
      packageName = "no-case";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/no-case/-/no-case-3.0.4.tgz";
        sha512 = "fgAN3jGAh+RoxUGZHTSOLJIqUc2wmoBwGR4tbpNAKmmovFoWq0OdRkb0VkldReO2a2iBT/OEulG9XSUc10r3zg==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha512 = "lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==";
      };
    };
    "param-case-3.0.4" = {
      name = "param-case";
      packageName = "param-case";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/param-case/-/param-case-3.0.4.tgz";
        sha512 = "RXlj7zCYokReqWpOPH9oYivUzLYZ5vAPIfEmCTNViosC78F8F0H9y7T7gG2M39ymgutxF5gcFEsyZQSph9Bp3A==";
      };
    };
    "pascal-case-3.1.2" = {
      name = "pascal-case";
      packageName = "pascal-case";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pascal-case/-/pascal-case-3.1.2.tgz";
        sha512 = "uWlGT3YSnK9x3BQJaOdcZwrnV6hPpd8jFH1/ucpiLRPh/2zCVJKS19E4GvYHvaCcACn3foXZ0cLB9Wrx1KGe5g==";
      };
    };
    "path-case-3.0.4" = {
      name = "path-case";
      packageName = "path-case";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-case/-/path-case-3.0.4.tgz";
        sha512 = "qO4qCFjXqVTrcbPt/hQfhTQ+VhFsqNKOPtytgNKkKxSoEp3XPUQ8ObFuePylOIok5gjn69ry8XiULxCwot3Wfg==";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha512 = "AVbw3UJ2e9bq64vSaS9Am0fje1Pa8pbGqTTsmXfaIiMpnr5DlDhfJOuLj9Sf95ZPVDAUerDfEk88MPmPe7UCQg==";
      };
    };
    "path-parse-1.0.7" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.7.tgz";
        sha512 = "LDJzPVEEEPR+y48z93A0Ed0yXb8pAByGWo/k5YYdYgpY2/2EsOsksJrq7lOHxryrVOn1ejG6oAp8ahvOIQD8sw==";
      };
    };
    "pretty-print-error-1.1.1" = {
      name = "pretty-print-error";
      packageName = "pretty-print-error";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pretty-print-error/-/pretty-print-error-1.1.1.tgz";
        sha512 = "xl5LI8vnfNExJzIpCeyoTVGHsKCyX5GSrK8IPoy6FJZQotqveE41guzwwPTEAWLJAcuq1s5xz4EbGQvM/KGwjw==";
      };
    };
    "rechoir-0.6.2" = {
      name = "rechoir";
      packageName = "rechoir";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rechoir/-/rechoir-0.6.2.tgz";
        sha512 = "HFM8rkZ+i3zrV+4LQjwQ0W+ez98pApMGM3HUrN04j3CqzPOzl9nmP15Y8YXNm8QHGv/eacOVEjqhmWpkRV0NAw==";
      };
    };
    "resolve-1.22.1" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.22.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.22.1.tgz";
        sha512 = "nBpuuYuY5jFsli/JIs1oldw6fOQCBioohqWZg/2hiaOybXOft4lonv85uDOKXdf8rhyK159cxU5cDcK/NKk8zw==";
      };
    };
    "sentence-case-3.0.4" = {
      name = "sentence-case";
      packageName = "sentence-case";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/sentence-case/-/sentence-case-3.0.4.tgz";
        sha512 = "8LS0JInaQMCRoQ7YUytAo/xUu5W2XnQxV2HI/6uM6U7CITS1RqPElr30V6uIqyMKM9lJGRVFy5/4CuzcixNYSg==";
      };
    };
    "shelljs-0.8.5" = {
      name = "shelljs";
      packageName = "shelljs";
      version = "0.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/shelljs/-/shelljs-0.8.5.tgz";
        sha512 = "TiwcRcrkhHvbrZbnRcFYMLl30Dfov3HKqzp5tO5b4pt6G/SezKcYhmDg15zXVBswHmctSAQKznqNW2LO5tTDow==";
      };
    };
    "snake-case-3.0.4" = {
      name = "snake-case";
      packageName = "snake-case";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/snake-case/-/snake-case-3.0.4.tgz";
        sha512 = "LAOh4z89bGQvl9pFfNF8V146i7o7/CqFPbqzYgP+yYzDIDeS9HaNFtXABamRW+AQzEVODcvE79ljJ+8a9YSdMg==";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "supports-preserve-symlinks-flag-1.0.0" = {
      name = "supports-preserve-symlinks-flag";
      packageName = "supports-preserve-symlinks-flag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-preserve-symlinks-flag/-/supports-preserve-symlinks-flag-1.0.0.tgz";
        sha512 = "ot0WnXS9fgdkgIcePe6RHNk1WA8+muPa6cSjeR3V8K27q9BB1rTE3R1p7Hv0z1ZyAc8s6Vvv8DIyWf681MAt0w==";
      };
    };
    "tslib-2.4.1" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.4.1.tgz";
        sha512 = "tGyy4dAjRIEwI7BzsB0lynWgOpfqjUdq91XXAlIWD2OwKBH7oCl/GZG/HT4BOHrTlPMOASlMQ7veyTqpmRcrNA==";
      };
    };
    "upper-case-2.0.2" = {
      name = "upper-case";
      packageName = "upper-case";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/upper-case/-/upper-case-2.0.2.tgz";
        sha512 = "KgdgDGJt2TpuwBUIjgG6lzw2GWFRCW9Qkfkiv0DxqHHLYJHmtmdUIKcZd8rHgFSjopVTlw6ggzCm1b8MFQwikg==";
      };
    };
    "upper-case-first-2.0.2" = {
      name = "upper-case-first";
      packageName = "upper-case-first";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/upper-case-first/-/upper-case-first-2.0.2.tgz";
        sha512 = "514ppYHBaKwfJRK/pNC6c/OxfGa0obSnAl106u97Ed0I625Nin96KAjttZF6ZL3e1XLtphxnqrOi9iWgm+u+bg==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha512 = "l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==";
      };
    };
  };
in
{
  "@suchipi/at-js" = nodeEnv.buildNodePackage {
    name = "_at_suchipi_slash_at-js";
    packageName = "@suchipi/at-js";
    version = "0.4.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@suchipi/at-js/-/at-js-0.4.0.tgz";
      sha512 = "CxaQaLKyH+UznHzoubI60j45x+ms7eZ8joAZ7Bnp5fhSJc5XPsS+Xc5fGaf5Y2TNyJREriDW/nIjG37S0qvt3w==";
    };
    dependencies = [
      sources."@babel/helper-validator-identifier-7.19.1"
      sources."@babel/highlight-7.18.6"
      sources."ansi-styles-3.2.1"
      sources."balanced-match-1.0.2"
      sources."brace-expansion-1.1.11"
      sources."camel-case-4.1.2"
      sources."capital-case-1.0.4"
      sources."chalk-2.4.2"
      sources."change-case-4.1.2"
      sources."clef-parse-0.1.2"
      sources."clefairy-0.2.1"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."concat-map-0.0.1"
      sources."constant-case-3.0.4"
      sources."dot-case-3.0.4"
      sources."escape-string-regexp-1.0.5"
      sources."fs.realpath-1.0.0"
      sources."function-bind-1.1.1"
      sources."glob-7.2.3"
      sources."has-1.0.3"
      sources."has-flag-3.0.0"
      sources."header-case-2.0.4"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."interpret-1.4.0"
      sources."is-core-module-2.11.0"
      sources."js-tokens-4.0.0"
      sources."json5-2.2.1"
      sources."kleur-4.1.5"
      sources."lodash-4.17.21"
      sources."lower-case-2.0.2"
      sources."make-module-env-1.0.1"
      sources."minimatch-3.1.2"
      sources."no-case-3.0.4"
      sources."once-1.4.0"
      sources."param-case-3.0.4"
      sources."pascal-case-3.1.2"
      sources."path-case-3.0.4"
      sources."path-is-absolute-1.0.1"
      sources."path-parse-1.0.7"
      sources."pretty-print-error-1.1.1"
      sources."rechoir-0.6.2"
      sources."resolve-1.22.1"
      sources."sentence-case-3.0.4"
      sources."shelljs-0.8.5"
      sources."snake-case-3.0.4"
      sources."supports-color-5.5.0"
      sources."supports-preserve-symlinks-flag-1.0.0"
      sources."tslib-2.4.1"
      sources."upper-case-2.0.2"
      sources."upper-case-first-2.0.2"
      sources."wrappy-1.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "unix stdin-pipe-based tools for transforming data with JavaScript";
      homepage = "https://github.com/suchipi/at-js#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
